version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate
    ports:
      - "8081:8081"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - weaviate

  langchain:
    build:
      context: ./langchain
    ports:
      - "5000:5000"
    depends_on:
      - weaviate
